apiVersion: v1
kind: Service
metadata:
  name: cloud-svc
  namespace: cloud
spec:
  selector:
    app: cloud
  type: ClusterIP
  ports:
    - name: cloud-svc-http-port
      port: 8080
      targetPort: 8080

